
version : '3'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./01-create-user.sql:/docker-entrypoint-initdb.d/1.sql
      - ./create-db.sql:/docker-entrypoint-initdb.d/3.sql
      - ./02-create-products.sql:/docker-entrypoint-initdb.d/2.sql

