version : '3'
services:
  db:
    container_name: mysqldb
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommercedb
      MYSQL_USER: ecommerceapp
      MYSQL_PASSWORD: ecommerceapp
    ports:
      - "3306:3306"
    volumes:
      - ./create-product-category.sql:/docker-entrypoint-initdb.d/create-product-category.sql
      - ./create-product.sql:/docker-entrypoint-initdb.d/create-product.sql
      - ./insert.sql:/docker-entrypoint-initdb.d/insert.sql
